### ISSUE TITLE
No settings showing up in browser settings

### ISSUE THREAD

**Issue by Ryan-Gamin** [danm36/zen-browser-private-browsing-toolbar-highlighting#3]

**Comment by danm36** [comment]
A recent Zen update moved these settings into a separate tab on the settings page called 'Theme Store' (They were previously in Look and Feel). I've also double checked the latest Zen version (1.0.0-a.33 as of writing) and they are visible in the Theme Store tab.The README will be updated to account for this change.

**Comment by danm36** [comment]
Huh, as an additional comment, now the settings for _all_ themes has disappeared from my 'Theme Store' settings page. Looks like this might be a browser bug. From what I can tell, some fixes for that page will be going out with Zen version 1.0.0-a35.

**Comment by danm36** [comment]
This has been fixed as of 1.0.0-a.35.
